# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:18:43+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Path, Query

from models import (
    Code1,
    Credentials,
    FhirObservationPage,
    PatientManagement,
    PatientmanagementDiagnosesGetResponse,
    PatientmanagementLookuptypesGetResponse,
    PatientUserIdBasicGetResponse,
    User,
    UserToken,
    UserUserIdAvailableobservationheadingsGetResponse,
    UserUserIdObservationsCodeGetResponse,
    UserUserIdObservationsCodePatiententeredGetResponse,
    UserUserIdPatiententeredobservationheadingsGetResponse,
)

app = MCPProxy(
    description='The recommended REST API endpoints to be used when integrating with PatientView',
    termsOfService='https://www.patientview.org/#/terms',
    title='PatientView',
    version='1.0',
    servers=[{'url': 'https://www.patientview.org/'}],
)


@app.post(
    '/auth/login',
    description=""" Authenticate using username and password, returns token, which must be added to X-Auth-Token in header of all future requests """,
    tags=['user_authentication'],
)
def log_in(body: Credentials = None):
    """
    Log In
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/auth/logout/{token}', description=""" Log Out """, tags=['user_authentication']
)
def log_out(token: str):
    """
    Log Out
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/auth/{token}/basicuserinformation',
    description=""" Once logged in and have a token, get basic user information including group role membership """,
    tags=['user_profile_retrieval'],
)
def get_basic_user_information(token: str):
    """
    Get Basic User Information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/patient/{userId}/basic',
    description=""" Given a User ID, get basic patient information for a user from clinical data stored in FHIR """,
    tags=['user_profile_retrieval', 'patient_record_management'],
)
def get_basic_patient_details(user_id: int = Path(..., alias='userId')):
    """
    Get Basic Patient Information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/patientmanagement/diagnoses',
    description=""" getPatientManagementDiagnoses """,
    tags=['patient_record_management'],
)
def get_patient_management_diagnoses():
    """
    getPatientManagementDiagnoses
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/patientmanagement/lookuptypes',
    description=""" getPatientManagementLookupTypes """,
    tags=['patient_record_management', 'patient_observation_handling'],
)
def get_patient_management_lookup_types():
    """
    getPatientManagementLookupTypes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/patientmanagement/validate',
    description=""" validatePatientManagement """,
    tags=['patient_record_management'],
)
def validate_patient_management(body: PatientManagement = None):
    """
    validatePatientManagement
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/patientmanagement/{userId}/group/{groupId}/identifier/{identifierId}',
    description=""" getPatientManagement """,
    tags=['patient_record_management'],
)
def get_patient_management(
    user_id: int = Path(..., alias='userId'),
    group_id: int = Path(..., alias='groupId'),
    identifier_id: int = Path(..., alias='identifierId'),
):
    """
    getPatientManagement
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/patientmanagement/{userId}/group/{groupId}/identifier/{identifierId}',
    description=""" savePatientManagement """,
    tags=['patient_record_management'],
)
def save_patient_management(
    user_id: int = Path(..., alias='userId'),
    group_id: int = Path(..., alias='groupId'),
    identifier_id: int = Path(..., alias='identifierId'),
    body: PatientManagement = None,
):
    """
    savePatientManagement
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/patientmanagement/{userId}/group/{groupId}/identifier/{identifierId}/surgeries',
    description=""" savePatientManagementSurgeries """,
    tags=['patient_record_management'],
)
def save_patient_management_surgeries(
    user_id: int = Path(..., alias='userId'),
    group_id: int = Path(..., alias='groupId'),
    identifier_id: int = Path(..., alias='identifierId'),
    body: PatientManagement = None,
):
    """
    savePatientManagementSurgeries
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/user/{userId}/availableobservationheadings',
    description=""" Given a User ID retrieve a list of available observation types for that user (where they have observation data). """,
    tags=['patient_observation_handling'],
)
def get_available_observation_headings(user_id: int = Path(..., alias='userId')):
    """
    Get Available Observations Types For a User
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/user/{userId}/observations',
    description=""" Given a User ID and search parameters, retrieve a page of observations. """,
    tags=['patient_observation_handling', 'user_profile_retrieval'],
)
def get_observations_by_codes(
    user_id: int = Path(..., alias='userId'),
    code: Code1 = ...,
    limit: int = ...,
    offset: int = ...,
    order_direction: str = Query(..., alias='orderDirection'),
):
    """
    Get Observations of Multiple Types For a User
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/user/{userId}/observations/{code}',
    description=""" Given a User ID and observation code, retrieve all observations. """,
    tags=['patient_observation_handling'],
)
def get_observations_by_code(user_id: int = Path(..., alias='userId'), code: str = ...):
    """
    Get Observations of a Certain Type For a User
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/user/{userId}/observations/{code}/patiententered',
    description=""" Given a User ID and observation code, retrieve patient entered observations. """,
    tags=['patient_observation_handling', 'patient_record_management'],
)
def get_patient_entered_observations_by_code(
    user_id: int = Path(..., alias='userId'), code: str = ...
):
    """
    Get patient entered Observations of a Certain Type For a User
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/user/{userId}/patiententeredobservationheadings',
    description=""" Given a User ID retrieve a list of available observation types for that user (where they have patient entered observation data). """,
    tags=['patient_observation_handling'],
)
def get_patient_entered_observation_headings(user_id: int = Path(..., alias='userId')):
    """
    Get Available Patient Entered Observations Types For a User
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
