# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:18:43+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, RootModel


class ApiKey(BaseModel):
    expired: Optional[bool] = None
    expiryDate: Optional[datetime] = None
    key: Optional[str] = None


class Category(BaseModel):
    friendlyDescription: Optional[str] = None
    hidden: Optional[bool] = None
    icd10Description: Optional[str] = None
    id: Optional[int] = None
    number: Optional[int] = None


class SourceType(Enum):
    PATIENTVIEW = 'PATIENTVIEW'
    NHS_CHOICES = 'NHS_CHOICES'


class CodeCategory(BaseModel):
    category: Optional[Category] = None
    id: Optional[int] = None


class Value(Enum):
    UNIT_WEB_ADDRESS = 'UNIT_WEB_ADDRESS'
    TRUST_WEB_ADDRESS = 'TRUST_WEB_ADDRESS'
    PV_ADMIN_NAME = 'PV_ADMIN_NAME'
    PV_ADMIN_PHONE = 'PV_ADMIN_PHONE'
    PV_ADMIN_EMAIL = 'PV_ADMIN_EMAIL'
    UNIT_ENQUIRIES_PHONE = 'UNIT_ENQUIRIES_PHONE'
    UNIT_ENQUIRIES_EMAIL = 'UNIT_ENQUIRIES_EMAIL'
    APPOINTMENT_PHONE = 'APPOINTMENT_PHONE'
    APPOINTMENT_EMAIL = 'APPOINTMENT_EMAIL'
    OUT_OF_HOURS_INFO = 'OUT_OF_HOURS_INFO'


class Credentials(BaseModel):
    apiKey: Optional[str] = None
    password: Optional[str] = None
    username: Optional[str] = None


class ExternalStandard(BaseModel):
    description: Optional[str] = None
    id: Optional[int] = None
    name: Optional[str] = None


class Feature(BaseModel):
    created: Optional[datetime] = None
    description: Optional[str] = None
    id: Optional[int] = None
    lastUpdate: Optional[datetime] = None
    name: Optional[str] = None


class FhirContact(BaseModel):
    id: Optional[int] = None
    system: Optional[str] = None
    use: Optional[str] = None
    value: Optional[str] = None


class FhirIdentifier(BaseModel):
    id: Optional[int] = None
    label: Optional[str] = None
    value: Optional[str] = None


class FhirPractitioner(BaseModel):
    address1: Optional[str] = None
    address2: Optional[str] = None
    address3: Optional[str] = None
    address4: Optional[str] = None
    allowInviteGp: Optional[bool] = None
    contacts: Optional[List[FhirContact]] = None
    gender: Optional[str] = None
    groupCode: Optional[str] = None
    identifier: Optional[str] = None
    inviteDate: Optional[datetime] = None
    name: Optional[str] = None
    postcode: Optional[str] = None
    role: Optional[str] = None


class FhirProcedure(BaseModel):
    bodySite: Optional[str] = None
    id: Optional[int] = None
    type: Optional[str] = None


class GroupFeature(BaseModel):
    created: Optional[datetime] = None
    feature: Optional[Feature] = None
    id: Optional[int] = None
    lastUpdate: Optional[datetime] = None


class Location(BaseModel):
    address: Optional[str] = None
    created: Optional[datetime] = None
    email: Optional[str] = None
    id: Optional[int] = None
    label: Optional[str] = None
    lastUpdate: Optional[datetime] = None
    name: Optional[str] = None
    phone: Optional[str] = None
    web: Optional[str] = None


class Type(Enum):
    GROUP = 'GROUP'
    MENU = 'MENU'
    ROLE = 'ROLE'
    CODE_STANDARD = 'CODE_STANDARD'
    CODE_TYPE = 'CODE_TYPE'
    FEATURE_TYPE = 'FEATURE_TYPE'
    RELATIONSHIP_TYPE = 'RELATIONSHIP_TYPE'
    IDENTIFIER = 'IDENTIFIER'
    CONTACT_POINT_TYPE = 'CONTACT_POINT_TYPE'
    STATISTIC_TYPE = 'STATISTIC_TYPE'
    NEWS_TYPE = 'NEWS_TYPE'
    GENDER = 'GENDER'
    IBD_CROHNSLOCATION = 'IBD_CROHNSLOCATION'
    IBD_CROHNSPROXIMALTERMINALILEUM = 'IBD_CROHNSPROXIMALTERMINALILEUM'
    IBD_CROHNSPERIANAL = 'IBD_CROHNSPERIANAL'
    IBD_CROHNSBEHAVIOUR = 'IBD_CROHNSBEHAVIOUR'
    IBD_UCEXTENT = 'IBD_UCEXTENT'
    IBD_EGIMCOMPLICATION = 'IBD_EGIMCOMPLICATION'
    IBD_SURGERYMAINPROCEDURE = 'IBD_SURGERYMAINPROCEDURE'
    IBD_SMOKINGSTATUS = 'IBD_SMOKINGSTATUS'
    IBD_FAMILYHISTORY = 'IBD_FAMILYHISTORY'
    LINK_TYPE = 'LINK_TYPE'


class LookupType(BaseModel):
    created: Optional[datetime] = None
    description: Optional[str] = None
    id: Optional[int] = None
    lastUpdate: Optional[datetime] = None
    type: Optional[Type] = None


class Name(Enum):
    PATIENT = 'PATIENT'
    UNIT_ADMIN = 'UNIT_ADMIN'
    STAFF_ADMIN = 'STAFF_ADMIN'
    DISEASE_GROUP_ADMIN = 'DISEASE_GROUP_ADMIN'
    SPECIALTY_ADMIN = 'SPECIALTY_ADMIN'
    GLOBAL_ADMIN = 'GLOBAL_ADMIN'
    GP_ADMIN = 'GP_ADMIN'
    MEMBER = 'MEMBER'
    PUBLIC = 'PUBLIC'
    UNIT_ADMIN_API = 'UNIT_ADMIN_API'
    IMPORTER = 'IMPORTER'


class Role(BaseModel):
    description: Optional[str] = None
    id: Optional[int] = None
    name: Optional[Name] = None
    visible: Optional[bool] = None


class UUIDModel(RootModel[Any]):
    root: Any


class UserFeature(BaseModel):
    created: Optional[datetime] = None
    feature: Optional[Feature] = None
    id: Optional[int] = None
    lastUpdate: Optional[datetime] = None
    optInDate: Optional[datetime] = None
    optInHidden: Optional[bool] = None
    optInStatus: Optional[bool] = None
    optOutHidden: Optional[bool] = None


class PatientmanagementLookuptypesGetResponse(RootModel[List[LookupType]]):
    root: List[LookupType]


class Code1(RootModel[List[str]]):
    root: List[str]


class CodeExternalStandard(BaseModel):
    codeString: Optional[str] = None
    externalStandard: Optional[ExternalStandard] = None
    id: Optional[int] = None


class ContactPointType(BaseModel):
    description: Optional[str] = None
    id: Optional[int] = None
    lookupType: Optional[LookupType] = None
    value: Optional[Value] = None


class Lookup(BaseModel):
    created: Optional[datetime] = None
    description: Optional[str] = None
    descriptionFriendly: Optional[str] = None
    displayOrder: Optional[int] = None
    id: Optional[int] = None
    lastUpdate: Optional[datetime] = None
    lookupType: Optional[LookupType] = None
    value: Optional[str] = None


class Route(BaseModel):
    controller: Optional[str] = None
    created: Optional[datetime] = None
    displayOrder: Optional[int] = None
    id: Optional[int] = None
    lookup: Optional[Lookup] = None
    templateUrl: Optional[str] = None
    title: Optional[str] = None
    url: Optional[str] = None


class BaseGroup(BaseModel):
    code: Optional[str] = None
    groupType: Optional[Lookup] = None
    id: Optional[int] = None
    lastImportDate: Optional[datetime] = None
    name: Optional[str] = None
    parentCodes: Optional[List[str]] = None
    shortName: Optional[str] = None
    visible: Optional[bool] = None
    visibleToJoin: Optional[bool] = None


class ContactPoint(BaseModel):
    contactPointType: Optional[ContactPointType] = None
    content: Optional[str] = None
    created: Optional[datetime] = None
    id: Optional[int] = None
    lastUpdate: Optional[datetime] = None


class Link(BaseModel):
    created: Optional[datetime] = None
    displayOrder: Optional[int] = None
    id: Optional[int] = None
    lastUpdate: Optional[datetime] = None
    link: Optional[str] = None
    linkType: Optional[Lookup] = None
    name: Optional[str] = None


class Code(BaseModel):
    code: Optional[str] = None
    codeCategories: Optional[List[CodeCategory]] = None
    codeType: Optional[Lookup] = None
    created: Optional[datetime] = None
    description: Optional[str] = None
    displayOrder: Optional[int] = None
    externalStandards: Optional[List[CodeExternalStandard]] = None
    fullDescription: Optional[str] = None
    hideFromPatients: Optional[bool] = None
    id: Optional[int] = None
    lastUpdate: Optional[datetime] = None
    links: Optional[List[Link]] = None
    patientFriendlyName: Optional[str] = None
    removedExternally: Optional[bool] = None
    sourceType: Optional[SourceType] = None
    standardType: Optional[Lookup] = None


class Group(BaseModel):
    address1: Optional[str] = None
    address2: Optional[str] = None
    address3: Optional[str] = None
    childGroups: Optional[List[Group]] = None
    code: Optional[str] = None
    contactPoints: Optional[List[ContactPoint]] = None
    created: Optional[datetime] = None
    fhirResourceId: Optional[UUID] = None
    groupFeatures: Optional[List[GroupFeature]] = None
    groupType: Optional[Lookup] = None
    id: Optional[int] = None
    lastImportDate: Optional[datetime] = None
    lastUpdate: Optional[datetime] = None
    links: Optional[List[Link]] = None
    locations: Optional[List[Location]] = None
    name: Optional[str] = None
    parentGroups: Optional[List[Group]] = None
    postcode: Optional[str] = None
    sftpUser: Optional[str] = None
    shortName: Optional[str] = None
    visible: Optional[bool] = None
    visibleToJoin: Optional[bool] = None


class GroupRole(BaseModel):
    group: Optional[Group] = None
    id: Optional[int] = None
    role: Optional[Role] = None


class ObservationHeadingGroup(BaseModel):
    created: Optional[datetime] = None
    group: Optional[Group] = None
    id: Optional[int] = None
    panel: Optional[int] = None
    panelOrder: Optional[int] = None


class User(BaseModel):
    apiKey: Optional[ApiKey] = None
    canSwitchUser: Optional[bool] = None
    changePassword: Optional[bool] = None
    contactNumber: Optional[str] = None
    created: Optional[datetime] = None
    currentLogin: Optional[datetime] = None
    currentLoginIpAddress: Optional[str] = None
    dateOfBirth: Optional[datetime] = None
    deleted: Optional[bool] = None
    dummy: Optional[bool] = None
    email: Optional[str] = None
    emailVerified: Optional[bool] = None
    forename: Optional[str] = None
    groupRoles: Optional[List[GroupRole]] = None
    hideSecretWordNotification: Optional[bool] = None
    id: Optional[int] = None
    identifiers: Optional[List[Dict[str, Any]]] = None
    lastLogin: Optional[datetime] = None
    lastLoginIpAddress: Optional[str] = None
    latestDataReceivedBy: Optional[BaseGroup] = None
    latestDataReceivedDate: Optional[datetime] = None
    locked: Optional[bool] = None
    picture: Optional[str] = None
    roleDescription: Optional[str] = None
    secretWordIsSet: Optional[bool] = None
    surname: Optional[str] = None
    userFeatures: Optional[List[UserFeature]] = None
    username: Optional[str] = None


class UserToken(BaseModel):
    auditActions: Optional[List[str]] = None
    checkSecretWord: Optional[bool] = None
    created: Optional[datetime] = None
    expiration: Optional[datetime] = None
    externalStandards: Optional[List[ExternalStandard]] = None
    groupFeatures: Optional[List[Feature]] = None
    groupMessagingEnabled: Optional[bool] = None
    mustSetSecretWord: Optional[bool] = None
    patientFeatures: Optional[List[Feature]] = None
    patientMessagingFeatureTypes: Optional[List[str]] = None
    patientRoles: Optional[List[Role]] = None
    routes: Optional[List[Route]] = None
    secretWord: Optional[str] = None
    secretWordChoices: Optional[Dict[str, Any]] = None
    secretWordIndexes: Optional[List[str]] = None
    secretWordSalt: Optional[str] = None
    secretWordToken: Optional[str] = None
    securityRoles: Optional[List[Role]] = None
    shouldEnterCondition: Optional[bool] = None
    staffFeatures: Optional[List[Feature]] = None
    staffRoles: Optional[List[Role]] = None
    token: Optional[str] = None
    user: Optional[User] = None
    userFeatures: Optional[List[Feature]] = None
    userGroups: Optional[List[BaseGroup]] = None


class PatientmanagementDiagnosesGetResponse(RootModel[List[Code]]):
    root: List[Code]


class FhirAllergy(BaseModel):
    confidenceLevel: Optional[str] = None
    group: Optional[Group] = None
    id: Optional[int] = None
    identifier: Optional[str] = None
    infoSource: Optional[str] = None
    reaction: Optional[str] = None
    recordedDate: Optional[datetime] = None
    status: Optional[str] = None
    substance: Optional[str] = None
    type: Optional[str] = None


class FhirCondition(BaseModel):
    asserter: Optional[str] = None
    category: Optional[str] = None
    code: Optional[str] = None
    date: Optional[datetime] = None
    description: Optional[str] = None
    fullDescription: Optional[str] = None
    group: Optional[Group] = None
    id: Optional[int] = None
    identifier: Optional[str] = None
    links: Optional[List[Link]] = None
    notes: Optional[str] = None
    severity: Optional[str] = None
    status: Optional[str] = None


class FhirObservation(BaseModel):
    applies: Optional[datetime] = None
    bodySite: Optional[str] = None
    comments: Optional[str] = None
    comparator: Optional[str] = None
    diagram: Optional[str] = None
    group: Optional[Group] = None
    id: Optional[int] = None
    identifier: Optional[str] = None
    location: Optional[str] = None
    name: Optional[str] = None
    temporaryUuid: Optional[str] = None
    units: Optional[str] = None
    value: Optional[str] = None


class FhirPatient(BaseModel):
    address1: Optional[str] = None
    address2: Optional[str] = None
    address3: Optional[str] = None
    address4: Optional[str] = None
    contacts: Optional[List[FhirContact]] = None
    dateOfBirth: Optional[datetime] = None
    dateOfBirthNoTime: Optional[str] = None
    forename: Optional[str] = None
    gender: Optional[str] = None
    group: Optional[Group] = None
    groupCode: Optional[str] = None
    identifier: Optional[str] = None
    identifiers: Optional[List[FhirIdentifier]] = None
    postcode: Optional[str] = None
    practitioners: Optional[List[FhirPractitioner]] = None
    surname: Optional[str] = None


class ObservationHeading(BaseModel):
    code: Optional[str] = None
    created: Optional[datetime] = None
    decimalPlaces: Optional[int] = None
    defaultPanel: Optional[int] = None
    defaultPanelOrder: Optional[int] = None
    heading: Optional[str] = None
    id: Optional[int] = None
    infoLink: Optional[str] = None
    lastUpdate: Optional[datetime] = None
    maxGraph: Optional[float] = None
    minGraph: Optional[float] = None
    name: Optional[str] = None
    normalRange: Optional[str] = None
    observationHeadingGroups: Optional[List[ObservationHeadingGroup]] = None
    units: Optional[str] = None


class UserUserIdAvailableobservationheadingsGetResponse(
    RootModel[List[ObservationHeading]]
):
    root: List[ObservationHeading]


class UserUserIdObservationsCodeGetResponse(RootModel[List[FhirObservation]]):
    root: List[FhirObservation]


class UserUserIdObservationsCodePatiententeredGetResponse(
    RootModel[List[FhirObservation]]
):
    root: List[FhirObservation]


class UserUserIdPatiententeredobservationheadingsGetResponse(
    RootModel[List[ObservationHeading]]
):
    root: List[ObservationHeading]


class EntryStringListFhirObservation(BaseModel):
    key: Optional[List[FhirObservation]] = None


class FhirEncounter(BaseModel):
    date: Optional[datetime] = None
    encounterType: Optional[str] = None
    group: Optional[Group] = None
    id: Optional[int] = None
    identifier: Optional[str] = None
    links: Optional[List[Link]] = None
    observations: Optional[List[FhirObservation]] = None
    procedures: Optional[List[FhirProcedure]] = None
    status: Optional[str] = None


class Patient(BaseModel):
    diagnosisCodes: Optional[List[Code]] = None
    fhirAllergies: Optional[List[FhirAllergy]] = None
    fhirConditions: Optional[List[FhirCondition]] = None
    fhirEncounters: Optional[List[FhirEncounter]] = None
    fhirObservations: Optional[List[FhirObservation]] = None
    fhirPatient: Optional[FhirPatient] = None
    fhirPractitioners: Optional[List[FhirPractitioner]] = None
    group: Optional[Group] = None
    id: Optional[int] = None


class PatientManagement(BaseModel):
    condition: Optional[FhirCondition] = None
    encounters: Optional[List[FhirEncounter]] = None
    groupCode: Optional[str] = None
    identifier: Optional[str] = None
    observations: Optional[List[FhirObservation]] = None
    patient: Optional[FhirPatient] = None
    practitioners: Optional[List[FhirPractitioner]] = None


class PatientUserIdBasicGetResponse(RootModel[List[Patient]]):
    root: List[Patient]


class EntryLongMapStringListFhirObservation(BaseModel):
    key: Optional[List[EntryStringListFhirObservation]] = None


class FhirObservationPage(BaseModel):
    data: Optional[List[EntryLongMapStringListFhirObservation]] = None
    totalElements: Optional[int] = None
    totalPages: Optional[int] = None


Group.model_rebuild()
